### health check
# @name health
GET http://localhost:8080/health

### get products
# @name query_all
GET http://localhost:8080/v1/product

### get product
# @name query
GET http://localhost:8080/v1/product/1

### add products
# @name add
POST  http://localhost:8080/v1/product

{
    "name": "product sample1",
    "price": 1.4
}

### get products
# @name update
PUT  http://localhost:8080/v1/product

{
    "id": 1,
    "name": "product updated",
    "price": 1.5
}

### delete product
# @name delete
DELETE http://localhost:8080/v1/product/1
