# generate base64 of username:password
# run below command in browser console
# btoa("admin"+":"+"Admin_123")
# @access_token=value of btoa("admin"+":"+"Admin_123")

### health check
# @name health
GET http://localhost:8081/product-service/health
# Authorization: Basic {{access_token}}
.
### get products
# @name query_all
GET http://localhost:8081/product-service/v1/product

### get product
# @name query
GET http://localhost:8081/product-service/v1/product/1

### add products
# @name add
POST  http://localhost:8081/product-service/v1/product

{
    "name": "sample2",
    "price": 1.4
}

### get products
# @name update
PUT  http://localhost:8081/product-service/v1/product

{
    "id": 1,
    "name": "product updated",
    "price": 1.5
}

### delete product
# @name delete
DELETE http://localhost:8081/product-service/v1/product/1

